wandb_version: 1

activation:
  value: relu
architecture:
  value:
    hidden_sizes: 256 128
    num_layers: 2
batch_size:
  value: 128
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
optimizer:
  value: momentum
weight_init:
  value: xavier
