wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
dataset:
  value: mnist
epochs:
  value: 5
hidden_sizes:
  value: 256 128
learning_rate:
  value: 0.0005
loss:
  value: cross_entropy
model_path:
  value: src
num_layers:
  value: 2
optimizer:
  value: nadam
wandb_project:
  value: da6401
weight_decay:
  value: 0
weight_init:
  value: random
