_wandb:
    value:
        cli_version: 0.25.0
        e:
            hwymcg34d3k1nwid6todk2f43f1hel0h:
                args:
                    - -m
                    - src
                    - -d
                    - mnist
                    - -e
                    - "5"
                    - -b
                    - "64"
                    - -l
                    - cross_entropy
                    - -o
                    - rmsprop
                    - -lr
                    - "0.001"
                    - -nhl
                    - "3"
                    - -sz
                    - "128"
                    - "128"
                    - "128"
                    - -a
                    - relu
                    - -w_i
                    - xavier
                    - -w_p
                    - da6401
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 8
                cpu_count_logical: 12
                disk:
                    /:
                        total: "171299053568"
                        used: "30788358144"
                email: me22b190@smail.iitm.ac.in
                executable: /home/hp/da6401_assignment_1/venv/bin/python
                git:
                    commit: 3ab52fd09fedec8640292edfb48a28e092b419c5
                    remote: https://github.com/Sayantika592/da6401_assignment_1.git
                host: hp-Victus-by-HP-Gaming-Laptop-15-fa2xxx
                memory:
                    total: "15835955200"
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.42
                program: /home/hp/da6401_assignment_1/src/train.py
                python: CPython 3.13.7
                root: /home/hp/da6401_assignment_1
                startedAt: "2026-03-01T14:35:57.726146Z"
                writerId: hwymcg34d3k1nwid6todk2f43f1hel0h
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 3
                - 16
            "4": 3.13.7
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
activation:
    value: relu
batch_size:
    value: 64
dataset:
    value: mnist
epochs:
    value: 5
hidden_sizes:
    value:
        - 128
        - 128
        - 128
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
model_path:
    value: src
num_layers:
    value: 3
optimizer:
    value: rmsprop
wandb_project:
    value: da6401
weight_decay:
    value: 0
weight_init:
    value: xavier
