_wandb:
    value:
        cli_version: 0.25.0
        e:
            e4rc9x12z8yshtwvlweaazsfzxbwiqyb:
                args:
                    - --activation=sigmoid
                    - --batch_size=128
                    - --dataset=mnist
                    - --epochs=5
                    - --hidden_sizes=128 64
                    - --learning_rate=0.005
                    - --loss=cross_entropy
                    - --model_path=src
                    - --num_layers=2
                    - --optimizer=adam
                    - --wandb_project=da6401
                    - --weight_decay=0
                    - --weight_init=xavier
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 8
                cpu_count_logical: 12
                disk:
                    /:
                        total: "171299053568"
                        used: "31230074880"
                email: me22b190@smail.iitm.ac.in
                executable: /home/hp/da6401_assignment_1/venv/bin/python
                git:
                    commit: b56b6f47865cc3bc0200b9e7360c562df06fc28a
                    remote: https://github.com/Sayantika592/da6401_assignment_1.git
                host: hp-Victus-by-HP-Gaming-Laptop-15-fa2xxx
                memory:
                    total: "15835955200"
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.42
                program: /home/hp/da6401_assignment_1/src/train.py
                python: CPython 3.13.7
                root: /home/hp/da6401_assignment_1
                startedAt: "2026-03-02T18:09:26.003432Z"
                writerId: e4rc9x12z8yshtwvlweaazsfzxbwiqyb
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 14
                - 16
            "4": 3.13.7
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
activation:
    value: sigmoid
batch_size:
    value: 128
dataset:
    value: mnist
epochs:
    value: 5
hidden_sizes:
    value: 128 64
learning_rate:
    value: 0.005
loss:
    value: cross_entropy
model_path:
    value: src
num_layers:
    value: 2
optimizer:
    value: adam
wandb_project:
    value: da6401
weight_decay:
    value: 0
weight_init:
    value: xavier
