wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
hidden_sizes:
  value: 128 64 32
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: sgd
weight_init:
  value: random
